version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - resume_SDLC_architect.pdf
    - links/*
    - styles/*
    - images/*
    - dist/bundle.js
